name: Fork Smoke Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  fork-smoke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fork smoke test
      id: run_fork_smoke_test
      run: |
        python tinygrad/ci.py 27773355347

    - name: Upload log
      uses: actions/upload-artifact@v2
      with:
        name: run_log
        path: run_log.txt
